% AUTOMATICITYMODEL_SCRIPT   Generate MEX-function automaticityModel_mex from
%  automaticityModel.
% 5
% Script generated from project 'automaticityModel.prj' on 07-Jan-2018.
% 
% See also CODER, CODER.CONFIG, CODER.TYPEOF, CODEGEN.
% Generated by: coder -tocode automaticityModel -script automaticityModel_script.m
tic;
%% Create configuration object of class 'coder.MexCodeConfig'.
cfg = coder.config('mex');
cfg.EnableJIT = true;
cfg.EnableMexProfiling = true;
cfg.GenerateComments = false;

%% Define argument types for entry-point 'automaticityModel'.
ARGS = cell(1,1);
ARGS{1} = cell(2,1);

ARGS{1}{1} = struct;
ARGS{1}{1}.PRE_LEARNING_TRIALS = coder.typeof(0);
ARGS{1}{1}.LEARNING_TRIALS = coder.typeof(0);
ARGS{1}{1}.POST_LEARNING_TRIALS = coder.typeof(0);
ARGS{1}{1}.W_MAX = coder.typeof(0);
ARGS{1}{1} = coder.typeof(ARGS{1}{1});

ARGS{1}{2} = struct;
ARGS{1}{2}.FMRI_META_GROUP_RUN = coder.typeof(0);
ARGS{1}{2}.VIS_INPUT_FROM_PARM = coder.typeof(0);
ARGS{1}{2}.visualinput = coder.typeof(0,[Inf  2],[1 0]);
ARGS{1}{2} = coder.typeof(ARGS{1}{2});

%% Add necessary folders to path
addpath(genpath('.'));

%% Invoke MATLAB Coder.
codegen -config cfg automaticityModel -args ARGS{1}
toc;