disp("Loading all functions and classes into path ...");
init;
disp("Functions and classes loaded onto path.");

disp("Generating performant code ...");
compile;
disp("Performant code generated.");

disp("Running model ..");
optional_parms = struct( ...
	'VIS_INPUT_FROM_PARM', 0, ...
	'visualinput', zeros(2) ...
);
automaticityModel_mex( ...
    getmodelparams(ModelConfigButtonSwitch()), ...
	optional_parms ...
)